name: CI

on:
  push:
    branches: [ main, preview, "feature/**" ]
  pull_request:
    branches: [ main, preview ]
  workflow_dispatch:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Enable pnpm via Corepack
        run: |
          corepack enable
          corepack prepare pnpm@10 --activate
          pnpm -v
      - run: pnpm install --frozen-lockfile
      - run: pnpm run -s typecheck

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Enable pnpm via Corepack
        run: |
          corepack enable
          corepack prepare pnpm@10 --activate
          pnpm -v
      - run: pnpm install --frozen-lockfile
      - run: pnpm run -s lint

  build:
    runs-on: ubuntu-latest
    needs: [typecheck, lint]
    env:
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Enable pnpm via Corepack
        run: |
          corepack enable
          corepack prepare pnpm@10 --activate
          pnpm -v
      - run: pnpm install --frozen-lockfile
      - run: pnpm run -s build
